apiVersion: project.harbor.crossplane.io/v1alpha1
kind: ImmutableTagRule
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/immutabletagrule
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    disabled: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    repoMatching: '**'
    tagExcluding: latest
    tagMatching: v2.*

---

apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/immutabletagrule
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: acctest
