apiVersion: project.harbor.crossplane.io/v1alpha1
kind: MemberUser
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/memberuser
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    role: projectadmin
    userName: testing1

---

apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/memberuser
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: main
