apiVersion: project.harbor.crossplane.io/v1alpha1
kind: MemberGroup
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/membergroup
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    groupName: testing1
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    role: projectadmin
    type: oidc

---

apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/membergroup
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: main
