apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Webhook
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    address: https://webhook.domain.com
    eventsTypes:
    - DELETE_ARTIFACT
    - PULL_ARTIFACT
    - PUSH_ARTIFACT
    - QUOTA_EXCEED
    - QUOTA_WARNING
    - REPLICATION
    - SCANNING_FAILED
    - SCANNING_COMPLETED
    - TAG_RETENTION
    name: test_webhook
    notifyType: http
    projectId: ${harbor_project.main.id}

---

apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: test-project
