apiVersion: user.buttah.m.cloud/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider:
    email: john@smith.com
    fullName: John Smith
    passwordSecretRef:
      key: example-key
      name: example-secret
    username: john
