// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MemberUserInitParameters struct {

	// (String) The permissions that the entity will be granted.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (String) The name of the member entity.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type MemberUserObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The member id of the member.
	MemberID *float64 `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// (String) The project id of the project that the entity will have access to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The permissions that the entity will be granted.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (String) The name of the member entity.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type MemberUserParameters struct {

	// (String) The project id of the project that the entity will have access to.
	// +crossplane:generate:reference:type=github.com/globallogicuki/provider-harbor/apis/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) The permissions that the entity will be granted.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (String) The name of the member entity.
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

// MemberUserSpec defines the desired state of MemberUser
type MemberUserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MemberUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MemberUserInitParameters `json:"initProvider,omitempty"`
}

// MemberUserStatus defines the observed state of MemberUser.
type MemberUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MemberUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// MemberUser is the Schema for the MemberUsers API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type MemberUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userName) || (has(self.initProvider) && has(self.initProvider.userName))",message="spec.forProvider.userName is a required parameter"
	Spec   MemberUserSpec   `json:"spec"`
	Status MemberUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MemberUserList contains a list of MemberUsers
type MemberUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MemberUser `json:"items"`
}

// Repository type metadata.
var (
	MemberUser_Kind             = "MemberUser"
	MemberUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MemberUser_Kind}.String()
	MemberUser_KindAPIVersion   = MemberUser_Kind + "." + CRDGroupVersion.String()
	MemberUser_GroupVersionKind = CRDGroupVersion.WithKind(MemberUser_Kind)
)

func init() {
	SchemeBuilder.Register(&MemberUser{}, &MemberUserList{})
}
