apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |
    {
      "url": <registry url here>,
      "username": <username>,
      "password": <password>
    }
---
apiVersion: harbor.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials

