apiVersion: garbagecollection.harbor.crossplane.io/v1alpha1
kind: GarbageCollection
metadata:
  annotations:
    meta.upbound.io/example-id: garbagecollection/v1alpha1/garbagecollection
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    deleteUntagged: true
    schedule: Daily
    workers: 1
