apiVersion: robotaccount.crossplane.io/v1alpha1
kind: RobotAccount
metadata:
  annotations:
    meta.upbound.io/example-id: robotaccount/v1alpha1/robotaccount
  labels:
    testing.upbound.io/example-name: system
  name: system
spec:
  forProvider:
    description: system level robot account
    level: system
    name: example-system
    permissions:
    - access:
      - action: create
        resource: label
      kind: system
      namespace: /
    - access:
      - action: push
        resource: repository
      kind: project
      namespace: main
    - access:
      - action: pull
        resource: repository
      kind: project
      namespace: '*'
    secretSecretRef:
      key: attribute.password.result
      name: example-
      namespace: upbound-system

---

apiVersion: project.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: robotaccount/v1alpha1/robotaccount
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: main
