//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuth) DeepCopyInto(out *ConfigAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuth.
func (in *ConfigAuth) DeepCopy() *ConfigAuth {
	if in == nil {
		return nil
	}
	out := new(ConfigAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthInitParameters) DeepCopyInto(out *ConfigAuthInitParameters) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthInitParameters.
func (in *ConfigAuthInitParameters) DeepCopy() *ConfigAuthInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthList) DeepCopyInto(out *ConfigAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthList.
func (in *ConfigAuthList) DeepCopy() *ConfigAuthList {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthObservation) DeepCopyInto(out *ConfigAuthObservation) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthObservation.
func (in *ConfigAuthObservation) DeepCopy() *ConfigAuthObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthParameters) DeepCopyInto(out *ConfigAuthParameters) {
	*out = *in
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.LdapBaseDn != nil {
		in, out := &in.LdapBaseDn, &out.LdapBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapFilter != nil {
		in, out := &in.LdapFilter, &out.LdapFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupAdminDn != nil {
		in, out := &in.LdapGroupAdminDn, &out.LdapGroupAdminDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupBaseDn != nil {
		in, out := &in.LdapGroupBaseDn, &out.LdapGroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupFilter != nil {
		in, out := &in.LdapGroupFilter, &out.LdapGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupGID != nil {
		in, out := &in.LdapGroupGID, &out.LdapGroupGID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupMembership != nil {
		in, out := &in.LdapGroupMembership, &out.LdapGroupMembership
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupScope != nil {
		in, out := &in.LdapGroupScope, &out.LdapGroupScope
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupUID != nil {
		in, out := &in.LdapGroupUID, &out.LdapGroupUID
		*out = new(string)
		**out = **in
	}
	if in.LdapScope != nil {
		in, out := &in.LdapScope, &out.LdapScope
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchDn != nil {
		in, out := &in.LdapSearchDn, &out.LdapSearchDn
		*out = new(string)
		**out = **in
	}
	if in.LdapSearchPasswordSecretRef != nil {
		in, out := &in.LdapSearchPasswordSecretRef, &out.LdapSearchPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.LdapUID != nil {
		in, out := &in.LdapUID, &out.LdapUID
		*out = new(string)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.LdapVerifyCert != nil {
		in, out := &in.LdapVerifyCert, &out.LdapVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.OidcAdminGroup != nil {
		in, out := &in.OidcAdminGroup, &out.OidcAdminGroup
		*out = new(string)
		**out = **in
	}
	if in.OidcAutoOnboard != nil {
		in, out := &in.OidcAutoOnboard, &out.OidcAutoOnboard
		*out = new(bool)
		**out = **in
	}
	if in.OidcClientID != nil {
		in, out := &in.OidcClientID, &out.OidcClientID
		*out = new(string)
		**out = **in
	}
	if in.OidcClientSecretSecretRef != nil {
		in, out := &in.OidcClientSecretSecretRef, &out.OidcClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.OidcEndpoint != nil {
		in, out := &in.OidcEndpoint, &out.OidcEndpoint
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupFilter != nil {
		in, out := &in.OidcGroupFilter, &out.OidcGroupFilter
		*out = new(string)
		**out = **in
	}
	if in.OidcGroupsClaim != nil {
		in, out := &in.OidcGroupsClaim, &out.OidcGroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcName != nil {
		in, out := &in.OidcName, &out.OidcName
		*out = new(string)
		**out = **in
	}
	if in.OidcScope != nil {
		in, out := &in.OidcScope, &out.OidcScope
		*out = new(string)
		**out = **in
	}
	if in.OidcUserClaim != nil {
		in, out := &in.OidcUserClaim, &out.OidcUserClaim
		*out = new(string)
		**out = **in
	}
	if in.OidcVerifyCert != nil {
		in, out := &in.OidcVerifyCert, &out.OidcVerifyCert
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryAuthMode != nil {
		in, out := &in.PrimaryAuthMode, &out.PrimaryAuthMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthParameters.
func (in *ConfigAuthParameters) DeepCopy() *ConfigAuthParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthSpec) DeepCopyInto(out *ConfigAuthSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthSpec.
func (in *ConfigAuthSpec) DeepCopy() *ConfigAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigAuthStatus) DeepCopyInto(out *ConfigAuthStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigAuthStatus.
func (in *ConfigAuthStatus) DeepCopy() *ConfigAuthStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmail) DeepCopyInto(out *ConfigEmail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmail.
func (in *ConfigEmail) DeepCopy() *ConfigEmail {
	if in == nil {
		return nil
	}
	out := new(ConfigEmail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigEmail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailInitParameters) DeepCopyInto(out *ConfigEmailInitParameters) {
	*out = *in
	if in.EmailFrom != nil {
		in, out := &in.EmailFrom, &out.EmailFrom
		*out = new(string)
		**out = **in
	}
	if in.EmailHost != nil {
		in, out := &in.EmailHost, &out.EmailHost
		*out = new(string)
		**out = **in
	}
	if in.EmailInsecure != nil {
		in, out := &in.EmailInsecure, &out.EmailInsecure
		*out = new(bool)
		**out = **in
	}
	if in.EmailPort != nil {
		in, out := &in.EmailPort, &out.EmailPort
		*out = new(float64)
		**out = **in
	}
	if in.EmailSSL != nil {
		in, out := &in.EmailSSL, &out.EmailSSL
		*out = new(bool)
		**out = **in
	}
	if in.EmailUsername != nil {
		in, out := &in.EmailUsername, &out.EmailUsername
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailInitParameters.
func (in *ConfigEmailInitParameters) DeepCopy() *ConfigEmailInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailList) DeepCopyInto(out *ConfigEmailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigEmail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailList.
func (in *ConfigEmailList) DeepCopy() *ConfigEmailList {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigEmailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailObservation) DeepCopyInto(out *ConfigEmailObservation) {
	*out = *in
	if in.EmailFrom != nil {
		in, out := &in.EmailFrom, &out.EmailFrom
		*out = new(string)
		**out = **in
	}
	if in.EmailHost != nil {
		in, out := &in.EmailHost, &out.EmailHost
		*out = new(string)
		**out = **in
	}
	if in.EmailInsecure != nil {
		in, out := &in.EmailInsecure, &out.EmailInsecure
		*out = new(bool)
		**out = **in
	}
	if in.EmailPort != nil {
		in, out := &in.EmailPort, &out.EmailPort
		*out = new(float64)
		**out = **in
	}
	if in.EmailSSL != nil {
		in, out := &in.EmailSSL, &out.EmailSSL
		*out = new(bool)
		**out = **in
	}
	if in.EmailUsername != nil {
		in, out := &in.EmailUsername, &out.EmailUsername
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailObservation.
func (in *ConfigEmailObservation) DeepCopy() *ConfigEmailObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailParameters) DeepCopyInto(out *ConfigEmailParameters) {
	*out = *in
	if in.EmailFrom != nil {
		in, out := &in.EmailFrom, &out.EmailFrom
		*out = new(string)
		**out = **in
	}
	if in.EmailHost != nil {
		in, out := &in.EmailHost, &out.EmailHost
		*out = new(string)
		**out = **in
	}
	if in.EmailInsecure != nil {
		in, out := &in.EmailInsecure, &out.EmailInsecure
		*out = new(bool)
		**out = **in
	}
	if in.EmailPasswordSecretRef != nil {
		in, out := &in.EmailPasswordSecretRef, &out.EmailPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.EmailPort != nil {
		in, out := &in.EmailPort, &out.EmailPort
		*out = new(float64)
		**out = **in
	}
	if in.EmailSSL != nil {
		in, out := &in.EmailSSL, &out.EmailSSL
		*out = new(bool)
		**out = **in
	}
	if in.EmailUsername != nil {
		in, out := &in.EmailUsername, &out.EmailUsername
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailParameters.
func (in *ConfigEmailParameters) DeepCopy() *ConfigEmailParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailSpec) DeepCopyInto(out *ConfigEmailSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailSpec.
func (in *ConfigEmailSpec) DeepCopy() *ConfigEmailSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEmailStatus) DeepCopyInto(out *ConfigEmailStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEmailStatus.
func (in *ConfigEmailStatus) DeepCopy() *ConfigEmailStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigEmailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurity) DeepCopyInto(out *ConfigSecurity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurity.
func (in *ConfigSecurity) DeepCopy() *ConfigSecurity {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigSecurity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurityInitParameters) DeepCopyInto(out *ConfigSecurityInitParameters) {
	*out = *in
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurityInitParameters.
func (in *ConfigSecurityInitParameters) DeepCopy() *ConfigSecurityInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurityList) DeepCopyInto(out *ConfigSecurityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigSecurity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurityList.
func (in *ConfigSecurityList) DeepCopy() *ConfigSecurityList {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigSecurityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurityObservation) DeepCopyInto(out *ConfigSecurityObservation) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurityObservation.
func (in *ConfigSecurityObservation) DeepCopy() *ConfigSecurityObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurityParameters) DeepCopyInto(out *ConfigSecurityParameters) {
	*out = *in
	if in.CveAllowlist != nil {
		in, out := &in.CveAllowlist, &out.CveAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurityParameters.
func (in *ConfigSecurityParameters) DeepCopy() *ConfigSecurityParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecuritySpec) DeepCopyInto(out *ConfigSecuritySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecuritySpec.
func (in *ConfigSecuritySpec) DeepCopy() *ConfigSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecurityStatus) DeepCopyInto(out *ConfigSecurityStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecurityStatus.
func (in *ConfigSecurityStatus) DeepCopy() *ConfigSecurityStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigSecurityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystem) DeepCopyInto(out *ConfigSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystem.
func (in *ConfigSystem) DeepCopy() *ConfigSystem {
	if in == nil {
		return nil
	}
	out := new(ConfigSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemInitParameters) DeepCopyInto(out *ConfigSystemInitParameters) {
	*out = *in
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemInitParameters.
func (in *ConfigSystemInitParameters) DeepCopy() *ConfigSystemInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemList) DeepCopyInto(out *ConfigSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemList.
func (in *ConfigSystemList) DeepCopy() *ConfigSystemList {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemObservation) DeepCopyInto(out *ConfigSystemObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemObservation.
func (in *ConfigSystemObservation) DeepCopy() *ConfigSystemObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemParameters) DeepCopyInto(out *ConfigSystemParameters) {
	*out = *in
	if in.ProjectCreationRestriction != nil {
		in, out := &in.ProjectCreationRestriction, &out.ProjectCreationRestriction
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.RobotNamePrefix != nil {
		in, out := &in.RobotNamePrefix, &out.RobotNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.RobotTokenExpiration != nil {
		in, out := &in.RobotTokenExpiration, &out.RobotTokenExpiration
		*out = new(float64)
		**out = **in
	}
	if in.ScannerSkipUpdatePulltime != nil {
		in, out := &in.ScannerSkipUpdatePulltime, &out.ScannerSkipUpdatePulltime
		*out = new(bool)
		**out = **in
	}
	if in.StoragePerProject != nil {
		in, out := &in.StoragePerProject, &out.StoragePerProject
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemParameters.
func (in *ConfigSystemParameters) DeepCopy() *ConfigSystemParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemSpec) DeepCopyInto(out *ConfigSystemSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemSpec.
func (in *ConfigSystemSpec) DeepCopy() *ConfigSystemSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystemStatus) DeepCopyInto(out *ConfigSystemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystemStatus.
func (in *ConfigSystemStatus) DeepCopy() *ConfigSystemStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigSystemStatus)
	in.DeepCopyInto(out)
	return out
}
