apiVersion: robotaccount.harbor.crossplane.io/v1alpha1
kind: RobotAccount
metadata:
  annotations:
    meta.upbound.io/example-id: robotaccount/v1alpha1/robotaccount
  labels:
    testing.upbound.io/example-name: projectbot 
  name: projectbot
spec:
  forProvider:
    description: project level robot account
    level: project
    name: example-project-robot
    permissions:
    - access:
      - action: push
        resource: repository
      - action: pull
        resource: repository
      kind: project
      namespace: projectbot 
    secretSecretRef:
      key: attribute.password.result
      name: example-
      namespace: upbound-system

---

apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: robotaccount/v1alpha1/robotaccount
  labels:
    testing.upbound.io/example-name: projectbot
  name: projectbot
spec:
  forProvider:
    name: projectbot
