//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetentionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyInitParameters) DeepCopyInto(out *RetentionPolicyInitParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyInitParameters.
func (in *RetentionPolicyInitParameters) DeepCopy() *RetentionPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyList) DeepCopyInto(out *RetentionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RetentionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyList.
func (in *RetentionPolicyList) DeepCopy() *RetentionPolicyList {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetentionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyObservation) DeepCopyInto(out *RetentionPolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyObservation.
func (in *RetentionPolicyObservation) DeepCopy() *RetentionPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyParameters) DeepCopyInto(out *RetentionPolicyParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]RuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyParameters.
func (in *RetentionPolicyParameters) DeepCopy() *RetentionPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicySpec) DeepCopyInto(out *RetentionPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicySpec.
func (in *RetentionPolicySpec) DeepCopy() *RetentionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicyStatus) DeepCopyInto(out *RetentionPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicyStatus.
func (in *RetentionPolicyStatus) DeepCopy() *RetentionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleInitParameters) DeepCopyInto(out *RuleInitParameters) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(float64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(float64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleInitParameters.
func (in *RuleInitParameters) DeepCopy() *RuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleObservation) DeepCopyInto(out *RuleObservation) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(float64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(float64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleObservation.
func (in *RuleObservation) DeepCopy() *RuleObservation {
	if in == nil {
		return nil
	}
	out := new(RuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParameters) DeepCopyInto(out *RuleParameters) {
	*out = *in
	if in.AlwaysRetain != nil {
		in, out := &in.AlwaysRetain, &out.AlwaysRetain
		*out = new(bool)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MostRecentlyPulled != nil {
		in, out := &in.MostRecentlyPulled, &out.MostRecentlyPulled
		*out = new(float64)
		**out = **in
	}
	if in.MostRecentlyPushed != nil {
		in, out := &in.MostRecentlyPushed, &out.MostRecentlyPushed
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPull != nil {
		in, out := &in.NDaysSinceLastPull, &out.NDaysSinceLastPull
		*out = new(float64)
		**out = **in
	}
	if in.NDaysSinceLastPush != nil {
		in, out := &in.NDaysSinceLastPush, &out.NDaysSinceLastPush
		*out = new(float64)
		**out = **in
	}
	if in.RepoExcluding != nil {
		in, out := &in.RepoExcluding, &out.RepoExcluding
		*out = new(string)
		**out = **in
	}
	if in.RepoMatching != nil {
		in, out := &in.RepoMatching, &out.RepoMatching
		*out = new(string)
		**out = **in
	}
	if in.TagExcluding != nil {
		in, out := &in.TagExcluding, &out.TagExcluding
		*out = new(string)
		**out = **in
	}
	if in.TagMatching != nil {
		in, out := &in.TagMatching, &out.TagMatching
		*out = new(string)
		**out = **in
	}
	if in.UntaggedArtifacts != nil {
		in, out := &in.UntaggedArtifacts, &out.UntaggedArtifacts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParameters.
func (in *RuleParameters) DeepCopy() *RuleParameters {
	if in == nil {
		return nil
	}
	out := new(RuleParameters)
	in.DeepCopyInto(out)
	return out
}
