/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ImmutableTagRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MemberGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MemberUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RetentionPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Webhook) Hub() {}
