// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RegistryInitParameters struct {

	// (String) The username / access id for the external container register.
	AccessID *string `json:"accessId,omitempty" tf:"access_id,omitempty"`

	// (String) The description of the external container register.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The url endpoint for the external container register ie "https://hub.docker.com"
	EndpointURL *string `json:"endpointUrl,omitempty" tf:"endpoint_url,omitempty"`

	// (Boolean) Verifies the certificate of the external container register. (Default: false)
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The name of the register.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the provider.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`
}

type RegistryObservation struct {

	// (String) The username / access id for the external container register.
	AccessID *string `json:"accessId,omitempty" tf:"access_id,omitempty"`

	// (String) The description of the external container register.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The url endpoint for the external container register ie "https://hub.docker.com"
	EndpointURL *string `json:"endpointUrl,omitempty" tf:"endpoint_url,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Verifies the certificate of the external container register. (Default: false)
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The name of the register.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the provider.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// (Number)
	RegistryID *float64 `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type RegistryParameters struct {

	// (String) The username / access id for the external container register.
	// +kubebuilder:validation:Optional
	AccessID *string `json:"accessId,omitempty" tf:"access_id,omitempty"`

	// (String, Sensitive) The password / access keys / token for the external container register.
	// +kubebuilder:validation:Optional
	AccessSecretSecretRef *v1.SecretKeySelector `json:"accessSecretSecretRef,omitempty" tf:"-"`

	// (String) The description of the external container register.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The url endpoint for the external container register ie "https://hub.docker.com"
	// +kubebuilder:validation:Optional
	EndpointURL *string `json:"endpointUrl,omitempty" tf:"endpoint_url,omitempty"`

	// (Boolean) Verifies the certificate of the external container register. (Default: false)
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The name of the register.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The name of the provider.
	// +kubebuilder:validation:Optional
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`
}

// RegistrySpec defines the desired state of Registry
type RegistrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RegistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryInitParameters `json:"initProvider,omitempty"`
}

// RegistryStatus defines the observed state of Registry.
type RegistryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Registry is the Schema for the Registrys API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type Registry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endpointUrl) || (has(self.initProvider) && has(self.initProvider.endpointUrl))",message="spec.forProvider.endpointUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerName) || (has(self.initProvider) && has(self.initProvider.providerName))",message="spec.forProvider.providerName is a required parameter"
	Spec   RegistrySpec   `json:"spec"`
	Status RegistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryList contains a list of Registrys
type RegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Registry `json:"items"`
}

// Repository type metadata.
var (
	Registry_Kind             = "Registry"
	Registry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Registry_Kind}.String()
	Registry_KindAPIVersion   = Registry_Kind + "." + CRDGroupVersion.String()
	Registry_GroupVersionKind = CRDGroupVersion.WithKind(Registry_Kind)
)

func init() {
	SchemeBuilder.Register(&Registry{}, &RegistryList{})
}
