apiVersion: project.buttah.m.cloud/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: crossplane-system
spec:
  forProvider:
    autoSbomGeneration: true
    enableContentTrust: true
    enableContentTrustCosign: false
    name: main
    public: false
    vulnerabilityScanner: Trivy
    vulnerabilityScanning: true
