/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/buttahtoast/provider-harbor/apis/cluster/config/v1alpha1"
	v1alpha1garbagecollection "github.com/buttahtoast/provider-harbor/apis/cluster/garbagecollection/v1alpha1"
	v1alpha1group "github.com/buttahtoast/provider-harbor/apis/cluster/group/v1alpha1"
	v1alpha1interrogationservices "github.com/buttahtoast/provider-harbor/apis/cluster/interrogationservices/v1alpha1"
	v1alpha1label "github.com/buttahtoast/provider-harbor/apis/cluster/label/v1alpha1"
	v1alpha1preheatinstance "github.com/buttahtoast/provider-harbor/apis/cluster/preheatinstance/v1alpha1"
	v1alpha1project "github.com/buttahtoast/provider-harbor/apis/cluster/project/v1alpha1"
	v1alpha1purgeauditlog "github.com/buttahtoast/provider-harbor/apis/cluster/purgeauditlog/v1alpha1"
	v1alpha1registry "github.com/buttahtoast/provider-harbor/apis/cluster/registry/v1alpha1"
	v1alpha1replication "github.com/buttahtoast/provider-harbor/apis/cluster/replication/v1alpha1"
	v1alpha1robotaccount "github.com/buttahtoast/provider-harbor/apis/cluster/robotaccount/v1alpha1"
	v1alpha1tasks "github.com/buttahtoast/provider-harbor/apis/cluster/tasks/v1alpha1"
	v1alpha1user "github.com/buttahtoast/provider-harbor/apis/cluster/user/v1alpha1"
	v1alpha1cluster "github.com/buttahtoast/provider-harbor/apis/cluster/v1alpha1"
	v1beta1 "github.com/buttahtoast/provider-harbor/apis/cluster/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1garbagecollection.SchemeBuilder.AddToScheme,
		v1alpha1group.SchemeBuilder.AddToScheme,
		v1alpha1interrogationservices.SchemeBuilder.AddToScheme,
		v1alpha1label.SchemeBuilder.AddToScheme,
		v1alpha1preheatinstance.SchemeBuilder.AddToScheme,
		v1alpha1project.SchemeBuilder.AddToScheme,
		v1alpha1purgeauditlog.SchemeBuilder.AddToScheme,
		v1alpha1registry.SchemeBuilder.AddToScheme,
		v1alpha1replication.SchemeBuilder.AddToScheme,
		v1alpha1robotaccount.SchemeBuilder.AddToScheme,
		v1alpha1tasks.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
