apiVersion: config.harbor.crossplane.io/v1alpha1
kind: ConfigSystem
metadata:
  annotations:
    meta.upbound.io/example-id: config/v1alpha1/configsystem
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    projectCreationRestriction: adminonly
    robotNamePrefix: harbor@
    robotTokenExpiration: 30
    storagePerProject: 100
