apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  name: crossplane-project
spec:
  forProvider:
    enableContentTrust: true
    enableContentTrustCosign: false
    name: crossplane-project
    public: false
    vulnerabilityScanning: true
