// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LabelInitParameters struct {

	// (String) The color of the label within harbor (Default: #FFFFF)
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) The Description of the label within harbor
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The of name of the label within harbor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the project with harbor.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type LabelObservation struct {

	// (String) The color of the label within harbor (Default: #FFFFF)
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) The Description of the label within harbor
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The of name of the label within harbor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the project with harbor.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String)
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type LabelParameters struct {

	// (String) The color of the label within harbor (Default: #FFFFF)
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) The Description of the label within harbor
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The of name of the label within harbor.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the project with harbor.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

// LabelSpec defines the desired state of Label
type LabelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LabelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LabelInitParameters `json:"initProvider,omitempty"`
}

// LabelStatus defines the observed state of Label.
type LabelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LabelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Label is the Schema for the Labels API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type Label struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   LabelSpec   `json:"spec"`
	Status LabelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LabelList contains a list of Labels
type LabelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Label `json:"items"`
}

// Repository type metadata.
var (
	Label_Kind             = "Label"
	Label_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Label_Kind}.String()
	Label_KindAPIVersion   = Label_Kind + "." + CRDGroupVersion.String()
	Label_GroupVersionKind = CRDGroupVersion.WithKind(Label_Kind)
)

func init() {
	SchemeBuilder.Register(&Label{}, &LabelList{})
}
