apiVersion: purgeauditlog.harbor.crossplane.io/v1alpha1
kind: PurgeAuditLog
metadata:
  annotations:
    meta.upbound.io/example-id: purgeauditlog/v1alpha1/purgeauditlog
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    auditRetentionHour: 24
    includeOperations: create,pull
    schedule: Daily
