apiVersion: replication.harbor.crossplane.io/v1alpha1
kind: Replication
metadata:
  annotations:
    meta.upbound.io/example-id: replication/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: push
  name: push
spec:
  forProvider:
    action: push
    name: test_push
    registryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: registry.harbor.crossplane.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: replication/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    endpointUrl: https://hub.docker.com
    name: test_docker_harbor
    providerName: docker-hub
